keys:
  - &users:
      - &marrero D1912EEBC3FBEBB4
  - &hosts:
    - &workstation age1dwu9ccy3t86c4tgd4ufs4jkmv572jfflkvdejm5kvjf95r3qsgus847qgd
    
creation_rules:
  - path_regex: hosts/workstation/secrets.yaml$
    key_groups:
      - age:
        - *workstation
        pgp:
        - *marrero
  - path_regex: hosts/ntb/secrets.yaml$
    key_groups:
      - age:
        - *workstation
        pgp:
        - *marrero
  - path_regex: hosts/lab/secrets.yaml$
    key_groups:
      - age:
        - *workstation
        pgp:
        - *marrero
